### PR TITLE
Stream messages between processes

### PR DESCRIPTION
**Pull request by noam-almog**
After playing with the library I found another buffer overrun on transport buffer.
To fix it I realized that we can just use streams instead of handling the stream ourselves so I removed all of the code that manages the chunks and used msgpack stream reader.
Once this is removed the max message size is redundant so I removed it from code and docs.

Update: fixed streaming, now we stream both ways (read and write)

### CODE REVIEW

**Comment by noam-almog** [comment]
@kwiatkk1 any chance this will be merged soon ?

**Comment by kwiatkk1** [comment]
@noam-almog yeah, but first I must investigate why tests are failing

**Comment by noam-almog** [comment]
@kwiatkk1 make sense, I noticed the test failure only yesterday. I cannot reproduce it on my machine at the moment, i will also try to investigate it.

**Comment by noam-almog** [comment]
@kwiatkk1 fixed all issues with tests, also updated the code to stream both ways, all tests are passing now and i think it's safe to merge, can you review ?

**Comment by noam-almog** [comment]
Deployed to prod, thanks :)

**Comment by kwiatkk1** [comment]
Hi Noam,

I think that this change (streaming) affects performance (see discussion on https://github.com/allegro/node-worker-nodes/issues/18). It makes sense, as streaming requires both host and worker processes to work at the same time, and waiting for one, blocks another :/

I think that the best solution is to make streaming an option, but not the default.

What do you think about that? Have you encountered any performance issues?

**Pull request merged**
